### ISSUE TITLE
Feature request - Units

### ISSUE THREAD

**Issue by heinekmadsen** [kpoppel/homeassistant-eforsyning#32]
When logging in to eforsyning website, the units is in MWh but the sensor in HA is in kWh.
Would it be possible to be able to choose which unit to use for the sensor, or have the other unit values populates as an attribute?

I'm aware that i can just create a template sensor the recalculate it into my favorite unit, but I think it would be a nice to have it all in the same sensor.

**Comment by kpoppel** [comment]
HomeAssistant seems to use kWh internally, but I am not really sure.  Some time ago I had to change everything to kWh a least to match number and unit.  Many releases of HA has passed since then.
  Another reason I made it kWh was to get around very small numbers, like this Summer where 1-5 kWh energy draw per 24h is not uncommon in a new house.  I also think using a unit of MWh cheats the mind a little because 0.010 MWh does not ring as loudly as 10 kWh.
 For now, using a template sensor to scale the unit seems like a fine solution.  Maybe if you would do others favour and post your yaml here for the template, then I can update the documentation with that tip.

**Comment by Bluhme1** [comment]
You are probably right. But as far as I can see, there are problems with the sensor energy total-used. Should be in MWh.
Maybe there are other too. Either with the comma misplaced or KWh instead of MWh. Maybe also expect_use and user_prognosis

And by the way. I cannot find the number in "Amount remaining" when I login to the app. Is it a calculated amount?

**Comment by kpoppel** [comment]
The number "Amount remaining" is directly from the returned data:
```
        {
            "ekstra": "kr.",
            "enhedPris": "",
            "linieType": "12",
            "antalEnheder": "",
            "enhed": "",
            "tekst": "Til indbetaling ",  <-- (or "Til udbetaling", always a positive number)
            "prisEnhed": "",
            "opl4": "",
            "opl3": "",
            "opl2": "",
            "opl1": "",
            "ialt": "965,90"
        },
```

It is changing on a daily basis as energy is consumed, either up or down.  I'll indicate if it is amount owed (positive number remaining), or in excess (negative number remaining)

**Comment by Bluhme1** [comment]
I have difficulties grasping the logic.
In my setup, I have negative numbers which are constantly increasing. Showing that I am going to have an increasing amount back.
Is that because I am using less kWh than expected (which I am).
And when the heating season begins The number will be decreasing and perhaps become positive.
Is that the the right interpretation?
And I cannot find the actual amount when I login to the app. The forecast in the app tells  me that I am going to have money back but not the same amount as your integration.

**Comment by kpoppel** [comment]
Maybe there is a better name for that attribute - and a sign reversal, if that would make it more intuitive :-) 
I am not sure what the logic behind this number is.  I am sure this will be more clear once the yearly report is in.  As it is the daily account of advance payments vs. expected consumption minus actual consumption, and with the current sign convention, this is how to interpret the number:

    Amount Remaining > 0 and increasing: I used more than current advance payments and keep using more than expected
    Amount Remaining > 0 and decreasing:  I used more than current advance payments and keep using less than expected

vice versa

    Amount Remaining < 0 and increasing:  I used less than current advance payments and keep using less than expected
    Amount Remaining < 0 and decreasing:  I used less than current advance payments and keep using more than expected

(an increasing negative number becomes more negative, and a decreasing negative number becomes less negative)

There is another number in the data which I am not putting in the attributes or as a sensor, because it does not change dato-to-day and seems to be just the next expected advance payment.  By itself it not interesting I think, because it does not reflect daily energy use, just the next payment.

**Comment by Bluhme1** [comment]
That was a very good explanation, and also what I had expected. Thank you very much. It is becoming an awesome integration.
May I suggest that you put the explanation into the readme on Github
