### ISSUE TITLE
Water temperatures do not report latest values

### ISSUE THREAD

**Issue by jnxxx** [kpoppel/homeassistant-eforsyning#7]
I noticed my return temperature was too high, what I have now adjusted.
However, the values reported in HA did not change, at least not enough, ever after several days.
Additionally, the reported forward temperature is much higher than the meter currently says.

It turns out it is because it reads "year data", from January 1st till yesterday. Probably to minimize data set.
While this works ok for used energy, for temperatures it seem to report an average or something. For sure not latest values, which I think would be the most useful.

I found this line, which I commented in:
#day=True, # TODO: Lets just see if pulling year data does not update daily.

Now I get the latest values for temperatures.
But it also means used energy is only for the latest day...

I realize this will get data for each day in current year, which is an unnecessary overhead. But I did not find another way most recent temperatures can be read.

A slight optimization could be done in this loop. Looks like it only needs to process the last entry in that array.
        for fl in result['ForbrugsLinjer']['TForbrugsLinje']:
           ...

**Comment by kpoppel** [comment]
I agree that temperature data is must useful with the actual daily measurement.  But I was not actually aware that the yearly value is a mean.  It makes sense though, and explains why it varies so slow on my end too :-)

I used the yearly dataset to not pull a lot of data from the REST endpoint.  I did it this way, not because of local resources but to do this pull daily and sort of stay off the ban list at the other end.  Perhaps this is just too much of a caution to take.  In principle anyone could log in daily on the website...

If you want to contribute a patch which takes the daily data instead of yearly, please submit it for review, and all can benefit from this.

**Comment by kpoppel** [comment]
I fixed this in v0.5.0 now.  The plugin now fetches data based on "daily", not "yearly", and this removed an averaging calculation done by eforsyning.
